"""
Clinical value analysis for LIDC binary malignancy predictions.

Inputs are ``test_predictions.csv`` files generated by
``LIDC_evaluate_lightning.py``. The script writes threshold curves, selected
operating points, confusion tables, and radiologist-score stratified summaries.

Run after ``LIDC_finalize_missing_outputs.py``:

    C:\\Users\\Ambro\\.conda\\envs\\torch-gpu\\python.exe data_analysis\\LIDC_clinical_value_analysis.py
"""

from __future__ import print_function

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SEARCH_ROOT = PROJECT_ROOT / "data" / "processed" / "model_results" / "lidc_lightning"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "data" / "processed" / "model_reports" / "lidc_clinical_value"
TABLE_DIR = PROJECT_ROOT / "data" / "processed" / "tables"
DEFAULT_METADATA_TABLES = [
    TABLE_DIR / "lidc_roi_3d_volume_manifest.csv",
    TABLE_DIR / "lidc_roi_binary_2d_slice_manifest.csv",
    TABLE_DIR / "lidc_roi_binary_split_manifest.csv",
    TABLE_DIR / "lidc_roi_labeled_manifest.csv",
    TABLE_DIR / "lidc_roi_consensus_manifest.csv",
]


def clean_value(value):
    if value is None:
        return ""
    text = str(value).strip()
    if text.lower() in ("none", "nan"):
        return ""
    return text


def safe_float(value):
    text = clean_value(value)
    if text == "":
        return None
    try:
        return float(text)
    except Exception:
        return None


def read_csv_rows(path):
    with Path(path).open("r", newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def write_csv(path, rows, fieldnames=None):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = list(rows)
    if fieldnames is None:
        fieldnames = []
        for row in rows:
            for key in row.keys():
                if key not in fieldnames:
                    fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_json(path, payload):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=True)


def discover_prediction_files(search_roots):
    paths = []
    for root in search_roots:
        root = Path(root)
        if root.exists():
            paths.extend(root.rglob("test_predictions.csv"))
    return sorted(set(paths))


def run_name_from_prediction_path(path):
    return Path(path).parent.name


def build_roi_index(metadata_tables):
    index = {}
    for table in metadata_tables:
        table = Path(table)
        if not table.exists():
            continue
        for row in read_csv_rows(table):
            roi_id = clean_value(row.get("roi_id"))
            if not roi_id:
                continue
            if roi_id not in index:
                index[roi_id] = {}
            for key, value in row.items():
                if clean_value(value) and not clean_value(index[roi_id].get(key)):
                    index[roi_id][key] = value
    return index


def positive_probability(row):
    for key in ("prob_malignant", "prob_high_risk", "prob_1"):
        value = safe_float(row.get(key))
        if value is not None:
            return value
    prob_cols = sorted([key for key in row if key.startswith("prob_")])
    if len(prob_cols) >= 2:
        return safe_float(row.get(prob_cols[-1]))
    return None


def is_binary_prediction_file(rows):
    if not rows:
        return False
    labels = set(clean_value(row.get("true_label")) for row in rows)
    probs = [key for key in rows[0] if key.startswith("prob_")]
    return "malignant" in labels or "prob_malignant" in probs or len(probs) == 2


def enrich_rows(rows, roi_index, run_name):
    out_rows = []
    for row in rows:
        out = dict(row)
        out["run_name"] = run_name
        roi_id = clean_value(out.get("roi_id"))
        for key, value in roi_index.get(roi_id, {}).items():
            if clean_value(value) and not clean_value(out.get(key)):
                out[key] = value
        out["positive_probability"] = positive_probability(out)
        out_rows.append(out)
    return out_rows


def labels_and_scores(rows):
    labels = []
    scores = []
    usable = []
    for row in rows:
        label = safe_float(row.get("true_label_id"))
        score = safe_float(row.get("positive_probability"))
        if label is None or score is None:
            continue
        labels.append(int(label))
        scores.append(float(score))
        usable.append(row)
    return np.asarray(labels, dtype=np.int64), np.asarray(scores, dtype=np.float64), usable


def metrics_at_threshold(labels, scores, threshold):
    preds = (scores >= float(threshold)).astype(np.int64)
    tp = int(((preds == 1) & (labels == 1)).sum())
    tn = int(((preds == 0) & (labels == 0)).sum())
    fp = int(((preds == 1) & (labels == 0)).sum())
    fn = int(((preds == 0) & (labels == 1)).sum())
    total = int(labels.size)
    sensitivity = tp / float(tp + fn) if (tp + fn) else 0.0
    specificity = tn / float(tn + fp) if (tn + fp) else 0.0
    precision = tp / float(tp + fp) if (tp + fp) else 0.0
    npv = tn / float(tn + fn) if (tn + fn) else 0.0
    accuracy = (tp + tn) / float(total) if total else 0.0
    f1 = 2 * precision * sensitivity / float(precision + sensitivity) if (precision + sensitivity) else 0.0
    return {
        "threshold": float(threshold),
        "sample_count": total,
        "tp": tp,
        "tn": tn,
        "fp": fp,
        "fn": fn,
        "accuracy": accuracy,
        "sensitivity_recall": sensitivity,
        "specificity": specificity,
        "precision_ppv": precision,
        "negative_predictive_value": npv,
        "f1": f1,
        "youden_index": sensitivity + specificity - 1.0,
    }


def threshold_grid(scores):
    values = sorted(set(float(value) for value in scores.tolist()))
    grid = [0.0, 0.5, 1.0]
    grid.extend(values)
    for value in values:
        grid.append(max(0.0, min(1.0, value - 1e-6)))
    return sorted(set(grid))


def auc_score(labels, scores):
    try:
        from sklearn.metrics import roc_auc_score
        if len(set(labels.tolist())) >= 2:
            return float(roc_auc_score(labels, scores))
    except Exception:
        pass
    return ""


def selected_operating_points(curve_rows):
    if not curve_rows:
        return []
    selections = []
    by_youden = max(curve_rows, key=lambda row: (float(row["youden_index"]), float(row["f1"])))
    selections.append(dict(by_youden, selection="best_youden"))
    by_f1 = max(curve_rows, key=lambda row: float(row["f1"]))
    selections.append(dict(by_f1, selection="best_f1"))
    default = min(curve_rows, key=lambda row: abs(float(row["threshold"]) - 0.5))
    selections.append(dict(default, selection="default_0_5"))
    for target in (0.90, 0.95):
        candidates = [row for row in curve_rows if float(row["sensitivity_recall"]) >= target]
        if candidates:
            chosen = max(candidates, key=lambda row: (float(row["specificity"]), float(row["threshold"])))
            selections.append(dict(chosen, selection="sensitivity_ge_{:.2f}".format(target)))
    return selections


def group_rows(rows, key):
    grouped = defaultdict(list)
    for row in rows:
        grouped[clean_value(row.get(key)) or "missing"].append(row)
    return grouped


def stratified_summary(rows, threshold):
    fields = [
        "label_confidence",
        "overall_consistency",
        "reader_agreement_category",
        "median_malignancy_score",
        "majority_calcification",
        "majority_spiculation",
        "majority_margin",
    ]
    output = []
    for field in fields:
        for value, group in sorted(group_rows(rows, field).items()):
            labels, scores, _ = labels_and_scores(group)
            if labels.size == 0:
                continue
            row = metrics_at_threshold(labels, scores, threshold)
            row["stratification_field"] = field
            row["stratification_value"] = value
            output.append(row)
    return output


def analyse_file(path, roi_index, output_dir):
    rows = read_csv_rows(path)
    if not is_binary_prediction_file(rows):
        return None
    run_name = run_name_from_prediction_path(path)
    enriched = enrich_rows(rows, roi_index, run_name)
    labels, scores, usable = labels_and_scores(enriched)
    if labels.size == 0:
        return None

    run_dir = Path(output_dir) / run_name
    run_dir.mkdir(parents=True, exist_ok=True)
    curve_rows = []
    for threshold in threshold_grid(scores):
        row = metrics_at_threshold(labels, scores, threshold)
        row["run_name"] = run_name
        curve_rows.append(row)
    selected = selected_operating_points(curve_rows)
    threshold_for_strata = float(selected[0]["threshold"]) if selected else 0.5
    strata = stratified_summary(usable, threshold_for_strata)
    for row in strata:
        row["run_name"] = run_name
        row["selected_threshold"] = threshold_for_strata

    write_csv(run_dir / "clinical_threshold_curve.csv", curve_rows)
    write_csv(run_dir / "clinical_selected_thresholds.csv", selected)
    write_csv(run_dir / "clinical_radiologist_strata_summary.csv", strata)
    write_csv(run_dir / "clinical_enriched_predictions.csv", enriched)
    metadata = {
        "run_name": run_name,
        "prediction_file": str(path),
        "sample_count": int(labels.size),
        "auc_roc": auc_score(labels, scores),
        "best_youden_threshold": selected[0]["threshold"] if selected else "",
        "outputs": {
            "threshold_curve": str(run_dir / "clinical_threshold_curve.csv"),
            "selected_thresholds": str(run_dir / "clinical_selected_thresholds.csv"),
            "radiologist_strata_summary": str(run_dir / "clinical_radiologist_strata_summary.csv"),
            "enriched_predictions": str(run_dir / "clinical_enriched_predictions.csv"),
        },
    }
    write_json(run_dir / "clinical_analysis_metadata.json", metadata)
    return metadata, curve_rows, selected, strata


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description="Compute clinical operating points for binary LIDC predictions.")
    parser.add_argument("--predictions", type=Path, nargs="*", default=None)
    parser.add_argument("--search-root", type=Path, nargs="*", default=[DEFAULT_SEARCH_ROOT])
    parser.add_argument("--metadata-tables", type=Path, nargs="*", default=DEFAULT_METADATA_TABLES)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    prediction_files = args.predictions if args.predictions else discover_prediction_files(args.search_root)
    prediction_files = [Path(path) for path in prediction_files if Path(path).exists()]
    if not prediction_files:
        raise FileNotFoundError("No test_predictions.csv files found. Run LIDC_finalize_missing_outputs.py first.")
    roi_index = build_roi_index(args.metadata_tables)
    payloads = []
    all_selected = []
    all_strata = []
    for path in prediction_files:
        result = analyse_file(path, roi_index, args.output_dir)
        if result is None:
            continue
        metadata, _, selected, strata = result
        payloads.append(metadata)
        all_selected.extend(selected)
        all_strata.extend(strata)
        print("Clinical analysis complete for {}".format(metadata["run_name"]))

    write_csv(args.output_dir / "all_binary_selected_thresholds.csv", all_selected)
    write_csv(args.output_dir / "all_binary_radiologist_strata_summary.csv", all_strata)
    write_json(args.output_dir / "clinical_analysis_index.json", {
        "run_count": len(payloads),
        "runs": payloads,
        "selected_thresholds_csv": str(args.output_dir / "all_binary_selected_thresholds.csv"),
        "radiologist_strata_csv": str(args.output_dir / "all_binary_radiologist_strata_summary.csv"),
    })
    print("Clinical value analysis index: {}".format(args.output_dir / "clinical_analysis_index.json"))


if __name__ == "__main__":
    main()
